services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: no
  mongo:
    image: mongo:7.0.12
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
    restart: no
  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: no
  streamlit-app:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: streamlitapp
    ports:
      - 8501:8501
    tty: true
    restart: no
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   ports:
  #     - 9090:9090
  #   restart: no
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - ./prometheus/prom_data:/prometheus
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   restart: no
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=grafana
  #   volumes:
  #     - ./grafana:/etc/grafana/provisioning/datasources
  # # wireshark:
  #   image: lscr.io/linuxserver/wireshark:latest
  #   container_name: wireshark
  #   cap_add:
  #     - NET_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Tokyo
  #   volumes:
  #     - ./wireshark:/config
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
    # restart: no
  # gitlab:
  #   image: "gitlab/gitlab-ce:latest"
  #   container_name: gitlab
  #   restart: no
  #   environment:
  #     - GITLAB_ROOT_PASSWORD=password
  #   ports:
  #     - "8000:80"
  #     - "8001:443"
  #     - "8002:22"
  #   volumes:
  #     - "/srv/gitlab/config:/etc/gitlab"
  #     - "/srv/gitlab/logs:/var/log/gitlab"
  #     - "/srv/gitlab/data:/var/opt/gitlab"
  #   shm_size: "256m"
  # gitlab-runner:
  #   image: "gitlab/gitlab-runner:latest"
  #   container_name: gitlab-runner
  #   restart: no
  #   volumes:
  #     - "/srv/gitlab-runner/config:/etc/gitlab-runner"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
# volumes:
#   prom_data:
